---
title: "s2_chd1_DE_analysis"
author: "ManasyanAL"
date: "13 08 2023"
output: html_document
---

## Importing the required libraries

```{r}
library(DESeq2)
library(ggplot2)
```


## Loading dataset

```{r}
Counts_s2 <- read.delim("data/s2_featurecounts.csv", header = TRUE, row.names = 1, sep = ",")
Counts_chd1 <- read.delim("data/chd1_featurecounts.csv", header = TRUE, row.names = 1, sep = ",")

```

```{r}
head(Counts_chd1, 10)
```

```{r}
dim(Counts_chd1)
```

```{r}
head(Counts_s2, 10)
```

```{r}
dim(Counts_s2)
```
## Remove genes with null expression

```{r}
Counts_s2 <- Counts_s2[which(rowSums(Counts_s2) > 0),]
Counts_chd1 <- Counts_chd1[which(rowSums(Counts_chd1) > 0),]
```

```{r}
dim(Counts_s2)
```

```{r}
dim(Counts_chd1)
```
## Definition of categorical features

```{r}
condition_s2 <- factor(c("C", "E", "C", "E"))
coldata_s2 <- data.frame(row.names = colnames(Counts_s2), condition_s2)
```

```{r}
coldata_s2
```

```{r}
condition_chd1 <- factor(c("C", "E", "C", "E"))
coldata_chd1 <- data.frame(row.names = colnames(Counts_chd1), condition_chd1)
```

```{r}
coldata_chd1
```


# DE for s2

```{r}
dds_s2 <- DESeqDataSetFromMatrix(countData = Counts_s2, colData = coldata_s2, design = ~condition_s2)
```

```{r}
dds_s2 <- DESeq(dds_s2)
```

```{r}
vsdata_s2 <- vst(dds_s2, blind = FALSE)
```

## PCA plot

```{r}
plotPCA(vsdata_s2, intgroup = "condition_s2")
```

## Plot dispersion estimates

```{r}
plotDispEsts(dds_s2)
```

## DE table 

```{r}
res_s2 <- results(dds_s2, contrast = c("condition_s2", "E", "C"))
```

```{r}
res_s2
```
## Definition of statistically significant changes

```{r}
sigs_s2 <- na.omit(res_s2)
```

```{r}
sigs_s2 <- sigs_s2[sigs_s2$padj < 0.05,]
```

```{r}
sigs_s2
```




# DE for chd1

```{r}
dds_chd1 <- DESeqDataSetFromMatrix(countData = Counts_chd1, colData = coldata_chd1, design = ~condition_chd1)
```

```{r}
dds_chd1 <- DESeq(dds_chd1)
```

```{r}
vsdata_chd1 <- vst(dds_chd1, blind = FALSE)
```

## PCA plot

```{r}
plotPCA(vsdata_chd1, intgroup = "condition_chd1")
```

## Plot dispersion estimates

```{r}
plotDispEsts(dds_chd1)
```

## DE table 

```{r}
res_chd1 <- results(dds_chd1, contrast = c("condition_chd1", "E", "C"))
```

```{r}
res_chd1
```

## Definition of statistically significant changes

```{r}
sigs_chd1 <- na.omit(res_chd1)
```

```{r}
sigs_chd1 <- sigs_chd1[sigs_chd1$padj < 0.05,]
```

```{r}
sigs_chd1
```


